name: Test
on:
  push:
    branches:
      - test_proposal

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: "true"

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
            dfx-version: "0.16.1"

      - name: Confirm successful installation
        run: dfx --version

      - name: Import DFX identity
        run: |
          touch actions_identity.pem
          echo "${{ secrets.TEST_IDENTITY_PRIVATE_KEY }}" > actions_identity.pem
          dfx identity import --storage-mode=plaintext actions actions_identity.pem
          dfx identity use actions

      - name: Start DFX Server
        run: dfx start --background

      # - name: Build
      #   run: |
      #       cd provision_canister
      #       rustup target add wasm32-unknown-unknown
      #       dfx canister create provision_canister_backend
      #       dfx build provision_canister_backend 

      #       hash=$(sha256sum < .dfx/local/canisters/provision_canister_backend/provision_canister_backend.wasm)
      #       echo "Module Hash: ${hash}"

      - name: Install quill from GitHub Releases
        run: |
            curl -LJO https://github.com/dfinity/quill/releases/download/v0.4.4/quill-linux-x86_64-musl
            mv quill-linux-x86_64-musl quill
            chmod +x quill
     
      - name: Confirm successful installation
        run: |
          ./quill sns -h
          
      - name: create an SNS proposal to upgrade the canister
        run: |
            cd provision_canister
            CANISTER_NAME=provision_canister_backend
            export CANISTER_ID=$(dfx canister id ${CANISTER_NAME} )
            mkdir -p "proposals/${CANISTER_NAME}"
            touch "proposals/${CANISTER_NAME}/upgrade.json"
            ../quill sns -h
            # ./quill sns \
            #     --pem-file actions_identity.pem \
            #     make-upgrade-canister-proposal \
            #     --title "Upgrade ${CANISTER_NAME} Canisters" \
            #     --summary "Upgrade ${CANISTER_NAME}" \
            #     --url '' \
            #     --target-canister-id $CANISTER_ID \
            #     --wasm-path .dfx/ic/canisters/${CANISTER_NAME}/${CANISTER_NAME}.wasm \
            #     ${{ secrets.TEST_IDENTITY_PRIVATE_KEY }} > "proposals/${CANISTER_NAME}/upgrade.json"
            ../quill send proposals/${CANISTER_NAME}/upgrade.json --yes

